services:
  kangaroo:
    build: .
    container_name: kangaroo
    ports:
      - "2222:22"
    volumes:
      - ./users.conf:/users.conf:ro
      - ./home:/home
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./connect-to.sh:/usr/local/bin/connect-to:ro
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    pids_limit: 100
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "22"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
